### ISSUE TITLE
Navbar does not turn blue to show pausing in browsers other than the one which did the pausing

### ISSUE THREAD

**Issue by butzopower** [concourse/atc#94] opened 2016-07-19 11:03 UTC
Steps to reproduce:

1. In a browser, open the web UI and look at a pipeline
2. In another browser, open the web UI and pause that pipeline; observe that the navbar turns blue
3. In the first browser, observe that the navbar does not turn blue
4. In the first browser, refresh
5. In the first browser, observe that the navbar is now blue

This comes up in the case where you have a CI monitor on the wall but are operating Concourse through a local browser.

We're using 1.4.1 through Vagrant.

Typed in by @tomwhoiscontrary

**Comment by vito** [comment] 2016-07-19 15:18
Dupe of https://github.com/concourse/concourse/issues/164 - thanks though

**Closed by vito** 2016-07-19 15:18 UTC
Labels: unscheduled

**Comment by tomwhoiscontrary** [comment] 2016-07-19 15:36
Aha. I did search before raising, but didn't think that someone might have reported this against the BOSH release. Cool.
